cache: packages
sudo: required
warnings_are_errors: false

services:
  - docker

stages:
  - test
  - name: documentation
    if: branch = master

jobs:
  include:
    - stage: test
      before_install:
        -  docker-compose run retrieverj
      script:
        -  docker-compose run --service-ports retrieverj julia test/runtests.jl || exit 1

    - stage: documentation
      language: julia
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; ENV["PYTHON"]=""; Pkg.add("PyCall")'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip