cache: packages
sudo: required
warnings_are_errors: false

services:
  - docker
before_install:
-  docker-compose  run retrieverj
script:
-  docker-compose run --service-ports retrieverj julia test/runtests.jl || exit 1
